### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by derekpock** [bharadwaj-raju/char-gtk-theme#1]
I'm interested in your theme, could you post some screenshots in your readme?

**Comment by bharadwaj-raju** [comment]
The theme is _nowhere_ near completion. It looks _just_ like the Numix GTK+ theme right now, later, when it's near completion, I shall post screenshots. For now, refer to the [concept art that inspired this](https://www.behance.net/gallery/28804097/Ubuntu-1604-Stupendously-Hot-Charmander-concept).

**Comment by derekpock** [comment]
Okay, thanks for clarifying.
